version: "3"
services:
    broker:
        container_name: mosquitto
        image: eclipse-mosquitto
        restart: always
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./mosquitto.log:/mosquitto/log/mosquitto.log
            - ./data:/mosquitto/data/
        restart: unless-stopped
        privileged: true
        network_mode: host
